import { Collection } from 'discord.js';
import { Command } from '../types';
import * as profile from './profile';
import * as daily from './daily';
import * as help from './help';
import * as wordoftheday from './wordoftheday';
import * as leaderboard from './leaderboard';
import * as join from './join';
import * as rps from './rps';
import * as coinflip from './coinflip';
import * as shop from './shop';
import * as buy from './buy';
import * as gift from './gift';
import * as radio from './radio';
import * as inventory from './inventory';
import * as setupWelcome from './setup-welcome';
import * as testWelcome from './test-welcome';
import * as settings from './settings';
import * as manageFeatures from './manage-features';
import * as sing from './sing';
import * as birthday from './birthday';
import * as confess from './confess';
import * as remind from './remind';
import * as poll from './poll';
import * as eightball from './8ball';
import * as wyr from './wyr';
import * as trivia from './trivia';
import * as tod from './tod';
import * as slots from './slots';
import * as setup from './setup';

export const commands = new Collection<string, Command>();

commands.set(profile.data.name, profile);
commands.set(daily.data.name, daily);
commands.set(help.data.name, help);
commands.set(wordoftheday.data.name, wordoftheday);
commands.set(leaderboard.data.name, leaderboard);
commands.set(join.data.name, join);
commands.set(rps.data.name, rps);
commands.set(coinflip.data.name, coinflip);
commands.set(shop.data.name, shop);
commands.set(buy.data.name, buy);
commands.set(gift.data.name, gift);
commands.set(radio.data.name, radio);
commands.set(inventory.data.name, inventory);
commands.set(setupWelcome.data.name, setupWelcome);
commands.set(testWelcome.data.name, testWelcome);
commands.set(settings.data.name, settings);
commands.set(manageFeatures.data.name, manageFeatures);
commands.set(sing.data.name, sing);
commands.set(birthday.data.name, birthday);
commands.set(confess.data.name, confess);
commands.set(remind.data.name, remind);
commands.set(poll.data.name, poll);
commands.set(eightball.data.name, eightball);
commands.set(wyr.data.name, wyr);
commands.set(trivia.data.name, trivia);
commands.set(tod.data.name, tod);
commands.set(slots.data.name, slots);
commands.set(setup.data.name, setup);